test_hammingDatabase_Clique_LETTERHIGH
test_hammingDatabase_Clique_LETTERLOW
test_hammingDatabase_Clique_LETTERMED
test_hammingDatabase_Clique_SAGRADAFAMILIA3D
test_hammingDatabase_Clique_ROTATIONZOOM
test_hammingDatabase_Clique_PALMPRINT
